// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjZVWYOjilfFFVcz19GzvezgbXlXHDPmY',
    appId: '1:1746668715:web:f2a8cc5de9c707ac503bee',
    messagingSenderId: '1746668715',
    projectId: 'appvideosflutter',
    authDomain: 'appvideosflutter.firebaseapp.com',
    storageBucket: 'appvideosflutter.firebasestorage.app',
    measurementId: 'G-GVQ8JV1ZZH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCX1hDiNOECatY7cblYtdMEBtb6ZaFRI7g',
    appId: '1:1746668715:android:515d286123cc5935503bee',
    messagingSenderId: '1746668715',
    projectId: 'appvideosflutter',
    storageBucket: 'appvideosflutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIG8JUCxWZ1JJ2tizgkG4ZY--dSaBYJSg',
    appId: '1:1746668715:ios:b231e9e0c8cdf0af503bee',
    messagingSenderId: '1746668715',
    projectId: 'appvideosflutter',
    storageBucket: 'appvideosflutter.firebasestorage.app',
    iosBundleId: 'com.fluttermapp.appsign',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIG8JUCxWZ1JJ2tizgkG4ZY--dSaBYJSg',
    appId: '1:1746668715:ios:b231e9e0c8cdf0af503bee',
    messagingSenderId: '1746668715',
    projectId: 'appvideosflutter',
    storageBucket: 'appvideosflutter.firebasestorage.app',
    iosBundleId: 'com.fluttermapp.appsign',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjZVWYOjilfFFVcz19GzvezgbXlXHDPmY',
    appId: '1:1746668715:web:39fd8ea7db0ec2bc503bee',
    messagingSenderId: '1746668715',
    projectId: 'appvideosflutter',
    authDomain: 'appvideosflutter.firebaseapp.com',
    storageBucket: 'appvideosflutter.firebasestorage.app',
    measurementId: 'G-W2HHXJP8RL',
  );

}